// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDfpoMRaeivEC0aqLETaCvIVBXRG-Ct0E',
    appId: '1:108550346269:web:920a148719c763c890d8f4',
    messagingSenderId: '108550346269',
    projectId: 'video-player-f696b',
    authDomain: 'video-player-f696b.firebaseapp.com',
    storageBucket: 'video-player-f696b.firebasestorage.app',
    measurementId: 'G-SEP81D2GPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdclwIHjH-CYBUg1opSMuXo2RsgSOxCto',
    appId: '1:108550346269:android:fb1f1ca77452f44190d8f4',
    messagingSenderId: '108550346269',
    projectId: 'video-player-f696b',
    storageBucket: 'video-player-f696b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbV9IZV8LxHn-fthjqkSCWxcbceuMucgQ',
    appId: '1:108550346269:ios:eafcf7dfec94e8c190d8f4',
    messagingSenderId: '108550346269',
    projectId: 'video-player-f696b',
    storageBucket: 'video-player-f696b.firebasestorage.app',
    iosBundleId: 'com.example.videoPlayerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbV9IZV8LxHn-fthjqkSCWxcbceuMucgQ',
    appId: '1:108550346269:ios:eafcf7dfec94e8c190d8f4',
    messagingSenderId: '108550346269',
    projectId: 'video-player-f696b',
    storageBucket: 'video-player-f696b.firebasestorage.app',
    iosBundleId: 'com.example.videoPlayerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDfpoMRaeivEC0aqLETaCvIVBXRG-Ct0E',
    appId: '1:108550346269:web:5a4c875aa4ab43f490d8f4',
    messagingSenderId: '108550346269',
    projectId: 'video-player-f696b',
    authDomain: 'video-player-f696b.firebaseapp.com',
    storageBucket: 'video-player-f696b.firebasestorage.app',
    measurementId: 'G-L3NZSDGSCD',
  );
}
