// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAJkmvJTQbegVRVdTDZTDrg3PT-bJqMBM',
    appId: '1:309835215337:web:57908bb526372fe21d9b78',
    messagingSenderId: '309835215337',
    projectId: 'dmaty-faf1e',
    authDomain: 'dmaty-faf1e.firebaseapp.com',
    storageBucket: 'dmaty-faf1e.firebasestorage.app',
    measurementId: 'G-2T8VMKVQQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9BO890upA6wjKGMyFPLvO5n6AvWTH1_I',
    appId: '1:309835215337:android:ca171ec44df8dc041d9b78',
    messagingSenderId: '309835215337',
    projectId: 'dmaty-faf1e',
    storageBucket: 'dmaty-faf1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUptzQj5BEvHfCtIQzEs6L6QUZBRK2ViQ',
    appId: '1:309835215337:ios:e27b03e37202be4c1d9b78',
    messagingSenderId: '309835215337',
    projectId: 'dmaty-faf1e',
    storageBucket: 'dmaty-faf1e.firebasestorage.app',
    iosBundleId: 'com.example.videoPlayerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUptzQj5BEvHfCtIQzEs6L6QUZBRK2ViQ',
    appId: '1:309835215337:ios:e27b03e37202be4c1d9b78',
    messagingSenderId: '309835215337',
    projectId: 'dmaty-faf1e',
    storageBucket: 'dmaty-faf1e.firebasestorage.app',
    iosBundleId: 'com.example.videoPlayerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAJkmvJTQbegVRVdTDZTDrg3PT-bJqMBM',
    appId: '1:309835215337:web:038cb3d1558e8c331d9b78',
    messagingSenderId: '309835215337',
    projectId: 'dmaty-faf1e',
    authDomain: 'dmaty-faf1e.firebaseapp.com',
    storageBucket: 'dmaty-faf1e.firebasestorage.app',
    measurementId: 'G-MJR36JSYR5',
  );

}